### ISSUE TITLE
K8SSAND-1680 ⁃ Documentation revamp

### ISSUE THREAD

**Issue by adejanovski** [k8ssandra/k8ssandra#1452]
Documentation on K8ssandra.io is currently confusing as you need to navigate your way through menus to access v2 docs.
It's also missing a lot of features that were introduced in K8ssandra-operator v1, and doesn't present a quick start guide showing how to enable all the components (the Reaper docs show how to use it, but not how to enable it).

```[tasklist]
### Tasks
- [x] #1454 
- [x] #1455 
- [x] #1457 
- [x] #1458
- [x] #1459
- [ ] #1453 
- [ ] #1461 
- [ ] #1460 
- [ ] #1456 
- [ ] https://github.com/k8ssandra/k8ssandra-operator/issues/791
- [ ] https://github.com/k8ssandra/k8ssandra-operator/issues/805
- [ ] #1570
- [ ] https://github.com/k8ssandra/k8ssandra-operator/issues/856
- [ ] https://github.com/k8ssandra/k8ssandra-operator/issues/874
- [ ] https://github.com/k8ssandra/k8ssandra/issues/1586
```

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1680) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1680
┆priority: Medium
